#!/bin/bash
#
# delayed job
#
# chkconfig: - 99 15
# description: start, stop, restart God (bet you feel powerful)
#

RETVAL=0

case "$1" in
    start)
      cd /home/app/crucible
      su app -c 'export PATH=$PATH:/home/ubuntu/.rbenv/versions/2.2.3/bin/ ; RAILS_ENV=production bin/delayed_job -n3 start'
      RETVAL=$?
      ;;
    stop)
      cd /home/app/crucible
      su app -c 'export PATH=$PATH:/home/ubuntu/.rbenv/versions/2.2.3/bin/ ; RAILS_ENV=production bin/delayed_job stop'
      RETVAL=$?
      ;;
    restart)
      cd /home/app/crucible
      su app -c 'export PATH=$PATH:/home/ubuntu/.rbenv/versions/2.2.3/bin/ ; RAILS_ENV=production bin/delayed_job restart'
      RETVAL=$?
      ;;
    status)
      cd /home/app/crucible
      su app -c 'export PATH=$PATH:/home/ubuntu/.rbenv/versions/2.2.3/bin/ ; RAILS_ENV=production bin/delayed_job status'
      RETVAL=$?
      ;;
    *)
      echo "Usage: delayed-job {start|stop|restart|status}"
      exit 1
  ;;
esac

exit $RETVAL
