apiVersion: v1
kind: Service
metadata:
  name: reference-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: reference-app
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: reference-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: reference-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: reference-app
    spec:
      containers:
      - image: gcr.io/genuine-segment-148215/reference-app:v3
        imagePullPolicy: IfNotPresent
        name: reference-app
        ports:
        - containerPort: 5000
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  name: reference-app
spec:
  containers:
  - image: gcr.io/genuine-segment-148215/reference-app:v3
    imagePullPolicy: IfNotPresent
    name: reference-app
    env:
    - name: BASE_URL
      value: http://s4s.tomwschneider.com
    ports:
    - containerPort: 5000
      protocol: TCP
    resources:
      requests:
        cpu: 100m
  dnsPolicy: ClusterFirst
  restartPolicy: Always
