---
- name: SMART
  client_id: api-test
  client_secret: api-secret
  scope: patient/*.read offline_access
  fhir_url: https://portal.demo.syncfor.science/api/fhir/
  redirect_uri: https://app.demo.syncfor.science/authorized
- name: Epic
  client_id: 94bdc785-64af-4e7e-87be-b7a285e9c1d6
  client_secret: argonaut
  scope: patient/*.read offline_access
  fhir_url: https://open-ic.epic.com/Argonaut/api/FHIR/Argonaut/
  redirect_uri: https://app.demo.syncfor.science/authorized
- name: Allscripts
  client_id: a1019f1e-1401-4d15-b7ee-a3d3635419fd
  client_secret: sFhnJIJwQaXWzF5d4aLmfxtXsdZdBCsiIsWONQq8YTaoXgdhcHU2dTibw/drsSjZ+G82CbAYVfTFIVR/0OhWJw==
  scope: patient/*.read offline_access
  fhir_url: https://uat-fhir.followmyhealth.com/api/
  redirect_uri: https://app.demo.syncfor.science/authorized
- name: eClinicalWorks
  client_id: 9a1158154dfa42caddbd0694a4e9bdc8
  client_secret: 8a093f6b3f64a67d0c4baee17994e0f5
  fhir_url: http://52.22.98.192:8080/FHIRServer/fhir/HEFBCA/
  scope: patient/*.read offline_access
  redirect_uri: https://app.demo.syncfor.science/authorized
- name: Cerner
  client_id: faa938c6-0ce8-4ae5-a36d-6716d2caffaf
  client_secret: WMWICQjLV4rWvY6GPOshoNGIayhDF4yk
  fhir_url: https://fhir-myrecord.sandboxcerner.com/dstu2/0b8a0111-e8e6-4c26-a91c-5069cbc6b1ca/
  scope: launch/patient patient/Patient.read patient/Encounter.read patient/Observation.read patient/Condition.read patient/MedicationOrder.read patient/MedicationStatement.read patient/MedicationDispense.read patient/MedicationAdministration.read patient/AllergyIntolerance.read patient/Procedure.read patient/Immunization.read patient/DocumentReference.read user/Practitioner.read offline_access
  redirect_uri: https://app.demo.syncfor.science/authorized
